// import { generateSummary } from '../../services/bedrockRuntime.service.js';
import { generateSummary } from '../../services/openai.service.js';

async function handler() {
  const transcript =
    "CORVUM HELP DESK: Thank you for calling KVM for service in English. Please press one if you know the extension. Thank you for calling Corvi help desk for service in English. Please press one. Thank you for calling for them help desk. How may I help you? \nMIKE TYSON: Uh, hi there. I'm calling about an existing request um, about some numbers porting in. I have the request number. Um, it is \nCORVUM HELP DESK: Uh \nMIKE TYSON: 48446 \nCORVUM HELP DESK: Sorry, what is it for \nMIKE TYSON: uh for numbers porting in \nCORVUM HELP DESK: for numbers ported in? Oh, I see. So 4846 \nMIKE TYSON: 48446. \nCORVUM HELP DESK: 048446. Thank you. So what I'll do is I'm happy to help. I'll take your information and we'll certainly go ahead and get um a call back to help you out with that one \nMIKE TYSON: Ok. \nCORVUM HELP DESK: moment, please. May I please have your name \nMIKE TYSON: Yeah, my name is Reed Shepherd. \nCORVUM HELP DESK: Shepherd? Is that S \nMIKE TYSON: Uh \nCORVUM HELP DESK: H E \nMIKE TYSON: S \nCORVUM HELP DESK: P H \nMIKE TYSON: C \nCORVUM HELP DESK: er D? \nMIKE TYSON: uh S C H E P. Er \nCORVUM HELP DESK: Oh, sorry, S C H E P \nMIKE TYSON: I, \nCORVUM HELP DESK: er \nMIKE TYSON: yeah, that's right. \nCORVUM HELP DESK: Thank you. May I please have the address or email address? \nMIKE TYSON: Uh, it's Reed at Surefire I T dot com. \nCORVUM HELP DESK: Thank you. That's re R E ID at Surefire, S U R E F I R E I T dot com. So are you looking \nMIKE TYSON: Uh \nCORVUM HELP DESK: for a message that came in? \nMIKE TYSON: uh no, I was hoping to talk to Yuri or Jason. Um, the numbers they, they say the numbers were ported over but we cannot see anything. \nCORVUM HELP DESK: I see. Alright, so yes, I will make sure I get it it to them right away. May I have a phone number to call you back on please? \nMIKE TYSON: Yeah, it's 780 uh 490 6705. Extension 112. \nCORVUM HELP DESK: Thank you. That's 7804906705. Extension 11 02 \nMIKE TYSON: Uh 112. No \nCORVUM HELP DESK: 112 cheaper \nMIKE TYSON: zero. \nCORVUM HELP DESK: creepers. I \nMIKE TYSON: Yeah. \nCORVUM HELP DESK: do apologize. \nMIKE TYSON: No, \nCORVUM HELP DESK: There \nMIKE TYSON: no \nCORVUM HELP DESK: we \nMIKE TYSON: worries. \nCORVUM HELP DESK: go. Alright. I will go ahead and get this submitted and ask Jason or someone to give you a return call as soon as possible. \nMIKE TYSON: Ok, thank you. \nCORVUM HELP DESK: Thank you so much Reed. Have a great day. \nMIKE TYSON: You too.";

  // await generateSummary(transcript);
  const summary =
    'Summary: Mike Tyson called the Corvum help desk to inquire about an existing request regarding numbers porting in. He provided his name, email address, and phone number for a call back. Mike mentioned that the numbers were ported over but they cannot see anything, and requested to speak to Yuri or Jason. The help desk representative assured Mike that they will pass on the information and have someone call him back.\n\nNext steps: The help desk representative will submit the request and ask Jason or someone to give Mike a return call as soon as possible. Mike Tyson will wait for the call back from the appropriate person to address his concerns regarding the numbers porting in.';

  console.log(summary.replace(/^Summary:/, '').trim());
}

handler();
